### ISSUE TITLE
[BUG] Tomato plant wilting

### ISSUE THREAD

**Issue by richardkriesman** [ByteWoofer/Gardening#1]
Hi all,

It seems this is already being addressed, but given the community's last update issue was two months ago, I figured it'd be good to get this officially reported so we can get some status updates on its resolution.

## Environment
Location: Garden, Tomato section
Version: 2019.04.27
Device: The ground???
OS: Outside (v1.0, as far as I'm aware)

## Steps to reproduce
1. Get a tomato plant
2. Plant it in a location (not 100% reproducible - this may be due to inadequate nutrients in the soil)
3. Wait several days
4. Observe that the tomato plant is wilting

## Expected result
The tomato plant appears green, with firm leaves. Eventually, it should flower and bear fruit.

## Actual result
The tomato plant is wilting and turning slightly brown. The documentation mentioned some refactoring around this, but we are unsure what the current status is.

## Severity
I believe this to be medium severity, as users are unable to access tomato fruits.

**Comment by richardkriesman** [comment]
I'm aware of the community's debate as to the classification of the tomato object, but it is botanically classified as a fruit. It may be worthwhile to have a meta thread on this, however.

**Comment by ByteWoofer** [comment]
This issue has been resolved as of recent internal refactors, official push of commit to public repository to be determined, this has yielded another bug as a result however as rabbits have began to take advantage of the growing fruits. (Identified by the disappearance of **every single tomato** from all of the plants. This has been opened as issue #2 .
